// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFt1UgnyET1sUemsXPyUjST7MquBZCJzU',
    appId: '1:572995758259:web:ccc94ff69d14d5f9e628c6',
    messagingSenderId: '572995758259',
    projectId: 'orderflow-general',
    authDomain: 'orderflow-general.firebaseapp.com',
    storageBucket: 'orderflow-general.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgVsWsjDN0y4_GZY7jF35gDNxQwUP6bA',
    appId: '1:572995758259:android:d371a203b4971a34e628c6',
    messagingSenderId: '572995758259',
    projectId: 'orderflow-general',
    storageBucket: 'orderflow-general.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRNq4yMtEiDaObwRAaSyvELLiiVZ_c0tg',
    appId: '1:572995758259:ios:062d9380589810d6e628c6',
    messagingSenderId: '572995758259',
    projectId: 'orderflow-general',
    storageBucket: 'orderflow-general.appspot.com',
    androidClientId: '572995758259-jr7l689mifb4a5tqpi7ngjm21bidig90.apps.googleusercontent.com',
    iosClientId: '572995758259-sjuch95lcd1raf32hmspr6mdmaagn75d.apps.googleusercontent.com',
    iosBundleId: 'com.zellow.ofgweb.ofgWeb',
  );
}
